-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "rejectionEmailSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "rejectionEmailError" TEXT;
